bad_passwords:
    - '18This_Is#Awesome?'
    - '000000'
    - '102030'
    - '1111'
    - '111111'
    - '11111111'
    - '112233'
    - '121212'
    - '123123'
    - '123123123'
    - '123321'
    - '1234'
    - '12345'
    - '123456'
    - '1234567'
    - '12345678'
    - '123456789'
    - '1234567890'
    - '123654'
    - '123qwe'
    - '131313'
    - '1q2w3e'
    - '1q2w3e4r'
    - '1qaz2wsx'
    - '2000'
    - '222222'
    - '555555'
    - '654321'
    - '666666'
    - '6969'
    - '696969'
    - '753951'
    - '7777777'
    - '987654321'
    - 'aaaaaa'
    - 'abc'
    - 'abc123'
    - 'abcd1234'
    - 'abcdef'
    - 'access'
    - 'adobe1'
    - 'adobe123'
    - 'adobeadobe'
    - 'alexander'
    - 'amanda'
    - 'andrea'
    - 'andrew'
    - 'anthony'
    - 'arion'
    - 'asdasd'
    - 'asdfasdf'
    - 'asdfgh'
    - 'asdfghj'
    - 'asdfghjkl'
    - 'ashley'
    - 'asshole'
    - 'austin'
    - 'azerty'
    - 'badboy'
    - 'bailey'
    - 'banana'
    - 'barney'
    - 'baseball'
    - 'batman'
    - 'bigdaddy'
    - 'bigdick'
    - 'bigdog'
    - 'bigtits'
    - 'bitch'
    - 'biteme'
    - 'black'
    - 'blowjob'
    - 'blowme'
    - 'booboo'
    - 'boomer'
    - 'boston'
    - 'brandon'
    - 'brandy'
    - 'bulldog'
    - 'buster'
    - 'camaro'
    - 'charles'
    - 'charlie'
    - 'cheese'
    - 'chelsea'
    - 'chicago'
    - 'chicken'
    - 'chocolate'
    - 'chris'
    - 'coffee'
    - 'compaq'
    - 'computer'
    - 'cookie'
    - 'corvette'
    - 'cowboy'
    - 'cowboys'
    - 'dakota'
    - 'dallas'
    - 'daniel'
    - 'diablo'
    - 'diamond'
    - 'dick'
    - 'dragon'
    - 'dreamweaver'
    - 'eagles'
    - 'edward'
    - 'enter'
    - 'falcon'
    - 'fdsa'
    - 'fender'
    - 'ferrari'
    - 'football'
    - 'freedom'
    - 'fuck'
    - 'fucker'
    - 'fuckme'
    - 'fuckyou'
    - 'gandalf'
    - 'gateway'
    - 'george'
    - 'ginger'
    - 'golfer'
    - 'guitar'
    - 'hammer'
    - 'hannah'
    - 'hardcore'
    - 'harley'
    - 'heather'
    - 'hello'
    - 'hockey'
    - 'horny'
    - 'hunter'
    - 'iceman'
    - 'iloveyou'
    - 'internet'
    - 'jackson'
    - 'james'
    - 'jennifer'
    - 'jessica'
    - 'john'
    - 'johnny'
    - 'johnson'
    - 'jordan'
    - 'joseph'
    - 'joshua'
    - 'junior'
    - 'justin'
    - 'killer'
    - 'knight'
    - 'lakers'
    - 'letmein'
    - 'liverpool'
    - 'love'
    - 'macromedia'
    - 'maggie'
    - 'marine'
    - 'martin'
    - 'master'
    - 'matrix'
    - 'matthew'
    - 'maverick'
    - 'melissa'
    - 'mercedes'
    - 'merlin'
    - 'metasushi'
    - 'michael'
    - 'michelle'
    - 'mickey'
    - 'mike'
    - 'miller'
    - 'money'
    - 'monkey'
    - 'monster'
    - 'morgan'
    - 'mustang'
    - 'nascar'
    - 'ncc1701'
    - 'nicole'
    - 'orange'
    - 'panties'
    - 'pass'
    - 'password'
    - 'password1'
    - 'patrick'
    - 'peanut'
    - 'pepper'
    - 'phoenix'
    - 'photoshop'
    - 'player'
    - 'please'
    - 'porn'
    - 'porsche'
    - 'princess'
    - 'purple'
    - 'pussy'
    - 'qazwsx'
    - 'qwerty'
    - 'qwertyuiop'
    - 'rabbit'
    - 'raiders'
    - 'ranger'
    - 'rangers'
    - 'richard'
    - 'robert'
    - 'samantha'
    - 'samsung'
    - 'scooby'
    - 'scooter'
    - 'secret'
    - 'sexy'
    - 'shadow'
    - 'silver'
    - 'smokey'
    - 'snoopy'
    - 'snoopy1'
    - 'soccer'
    - 'spanky'
    - 'sparky'
    - 'spider'
    - 'starwars'
    - 'steelers'
    - 'steven'
    - 'summer'
    - 'sunshine'
    - 'superman'
    - 'taylor'
    - 'tennis'
    - 'test'
    - 'thomas'
    - 'thunder'
    - 'tickets'
    - 'tiger'
    - 'tigers'
    - 'tigger'
    - 'trustno1'
    - 'welcome'
    - 'whatever'
    - 'william'
    - 'winter'
    - 'wizard'
    - 'xxxxxx'
    - 'yamaha'
    - 'yankees'
    - 'yellow'
    - 'zxcvbn'
    - 'zxcvbnm'
