<?php

/*
 * @package ArionCRM
 * @author Isaac Raway <iraway@metasushi [dot] com>
 * @author Antoinette Smith <asmith@metasushi [dot] com>
 * @link http://arioncrm.com/
 * @copyright (c)2015-2022. MetaSushi, LLC. All rights reserved. Your use of this software in any way indicates agreement
 * to the software license available currenty at http://arioncrm.com/ 
 * This open source edition is released under GPL 3.0. available at https://www.gnu.org/licenses/gpl-3.0.en.html
 */

namespace AppBundle\Entity;

/**
 * MailboxMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailboxMessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function createMessage($accountId, $mailboxId, $uid, $subject, $date, $body, $to, $from, $cc)
    {
        $message = new MailboxMessage();
        $message->setAccountId($accountId);
        $message->setMailboxId($mailboxId);
        $message->setImapUid($uid);
        $message->setSubject($subject);
        $message->setDate($date);
        $message->setBody($body);
        $message->setTo($to);
        $message->setFrom($from);
        $message->setCc($cc);
        
        $messageId = $this->saveMessage($message);
        return $this->findById($messageId);
    }

    /**
     * Helper to save a message
     */
    public function saveMessage(MailboxMessage $message)
    {
        if(!$message->getId()) {
           $this->getEntityManager()->persist($message);
        }
        $this->getEntityManager()->flush();
        return $message->getId();
    }
}
